sudo: required
services:
  - docker


before_install:
  - docker build -t peem16/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run peem16/react-test npm test -- --coverage

after_success:
  - docker build -t peem16/multi-client ./client
  - docker build -t peem16/multi-nginx ./nginx
  - docker build -t peem16/multi-server ./server
  - docker build -t peem16/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push peem16/multi-client
  - docker push peem16/multi-nginx
  - docker push peem16/multi-server
  - docker push peem16/multi-worker

deploy:
  edge: true
  provider: elastibeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-891401262083
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
